name: deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ec2-54-200-34-66.us-west-2.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/demo
            export DIR=$(date +%Y%m%d%H%M%S)
            git clone https://github.com/raptor-mvk/blue-green-deploy-demo.git $DIR
            sudo chown www-data:www-data $DIR -R
            cd $DIR
            sh ./deploy.sh
            cd ..
            unlink /var/www/demo/previous
            mv -T /var/www/demo/current /var/www/demo/previous
            ln -s /var/www/demo/$DIR /var/www/demo/current
            unset DIR