name: deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ec2-54-200-34-66.us-west-2.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www
            git clone https://github.com/raptor-mvk/blue-green-deploy-demo.git demo
            sudo chown www-data:www-data demo -R
            cd demo
            sh ./deploy.sh
